on:
  push:
    branches:
      - master
env:
  SemVer: 2.1.1
  Configuration: Release
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2 
    - uses: actions/setup-dotnet@51f68377c181a79065c61bd492bd49be4575c439 # pin@v1 
    - uses: nuget/setup-nuget@04b0c2b8d1b97922f67eca497d7cf0bf17b8ffe1 # pin@v1.0.5 
      with:
        nuget-version: 5.x
    - run: nuget restore
    - uses: microsoft/setup-msbuild@c26a08ba26249b81327e26f6ef381897b6a8754d # pin@v1 
    - name: build
      run: msbuild /p:Configuration=${{ env.Configuration }} /p:"Platform=Any CPU" /p:Version=${{ env.SemVer }}.${{ GITHUB.RUN_NUMBER }} /p:InformationalVersion=${{ env.SemVer }}
      shell: cmd
    - run: dotnet test -c Release --no-build src/DotNetCore.Tests/DotNetCore.Tests.csproj
    # glob pattern does not seem to work due to mix of .Net Core & Full Framework tests
    - run: dotnet vstest "src\testmodules\LocalizationTests\bin\${{ env.Configuration }}\net46\LocalizationTests.dll" --Framework:".NETFramework,Version=4.6"
    - run: dotnet vstest "src\ResourceEmbedder.Core.Tests\bin\${{ env.Configuration }}\net46\ResourceEmbedder.Core.Tests.dll" --Framework:".NETFramework,Version=4.6"
    - run: dotnet vstest "src\ResourceEmbedder.MsBuild.Tests\bin\${{ env.Configuration }}\net472\ResourceEmbedder.MsBuild.Tests.dll" --Framework:".NETFramework,Version=4.72"
    - run: |
        dotnet pack src/ResourceEmbedder.Core/ResourceEmbedder.Core.csproj -c ${{ env.Configuration }} -o release/packages -p:PackageVersion=${{ env.SemVer }} --no-build
        dotnet pack src/ResourceEmbedder.MsBuild/ResourceEmbedder.MsBuild.csproj -c ${{ env.Configuration }} -o release/packages -p:PackageVersion=${{ env.SemVer }} --no-build
    - uses: actions/upload-artifact@3446296876d12d4e3a0f3145a3c87e67bf0a16b5 # pin@v1 
      with:
        name: nuget
        path: release/packages
